"""Ingredient mappings for recipe filtering.

Defines dictionaries mapping dietary preferences and allergies to
ingredient keywords that should be excluded from recipes.
"""

from app.models.preferences import AllergyType, DietaryType

# Dietary type to excluded ingredients mapping
# Each dietary preference maps to a list of ingredients to exclude
DIETARY_EXCLUSIONS: dict[DietaryType, list[str]] = {
    DietaryType.VEGETARIAN: [
        # Poultry
        "chicken",
        "chicken breast",
        "chicken thigh",
        "chicken wing",
        "turkey",
        "duck",
        "goose",
        # Red meat
        "beef",
        "steak",
        "ground beef",
        "veal",
        "lamb",
        "mutton",
        # Pork
        "pork",
        "bacon",
        "ham",
        "sausage",
        "pancetta",
        "prosciutto",
        "chorizo",
        "salami",
        # Game
        "venison",
        "rabbit",
        # Seafood with meat characteristics
        "anchovy",
    ],
    DietaryType.VEGAN: [
        # All meats (same as vegetarian)
        "chicken",
        "chicken breast",
        "chicken thigh",
        "turkey",
        "duck",
        "beef",
        "steak",
        "ground beef",
        "veal",
        "lamb",
        "pork",
        "bacon",
        "ham",
        "sausage",
        # Dairy products
        "milk",
        "cheese",
        "cream",
        "butter",
        "yogurt",
        "yoghurt",
        "ghee",
        "whey",
        "casein",
        "parmesan",
        "mozzarella",
        "cheddar",
        "feta",
        "ricotta",
        "mascarpone",
        # Eggs
        "egg",
        "eggs",
        "mayonnaise",
        # Honey
        "honey",
        # Fish and seafood
        "fish",
        "salmon",
        "tuna",
        "cod",
        "shrimp",
        "prawn",
        "lobster",
        "crab",
        "anchovy",
    ],
    DietaryType.NO_PORK: [
        "pork",
        "bacon",
        "ham",
        "sausage",
        "pancetta",
        "prosciutto",
        "chorizo",
        "salami",
        "lard",
        "pork belly",
        "pork chop",
        "pork loin",
    ],
    DietaryType.NO_BEEF: [
        "beef",
        "steak",
        "ground beef",
        "beef mince",
        "veal",
        "brisket",
        "sirloin",
        "ribeye",
        "tenderloin",
    ],
    DietaryType.PESCETARIAN: [
        # Excludes land meats, allows fish/seafood
        "chicken",
        "chicken breast",
        "turkey",
        "duck",
        "beef",
        "steak",
        "ground beef",
        "veal",
        "lamb",
        "pork",
        "bacon",
        "ham",
        "sausage",
        "venison",
        "rabbit",
    ],
    DietaryType.HALAL: [
        # Pork and derivatives
        "pork",
        "bacon",
        "ham",
        "sausage",
        "pancetta",
        "prosciutto",
        "chorizo",
        "salami",
        "lard",
        "pork belly",
        # Alcohol
        "wine",
        "beer",
        "alcohol",
        "rum",
        "vodka",
        "whiskey",
        "brandy",
        "liqueur",
        "sherry",
        "marsala",
    ],
    DietaryType.KOSHER: [
        # Pork
        "pork",
        "bacon",
        "ham",
        "lard",
        "pancetta",
        "prosciutto",
        # Shellfish
        "shrimp",
        "prawn",
        "lobster",
        "crab",
        "clam",
        "mussel",
        "oyster",
        "scallop",
        # Mixing meat and dairy (can't be detected by ingredient alone,
        # but we exclude common combos)
    ],
}

# Allergy type to ingredient keywords mapping
# Each allergy maps to keywords that indicate presence of allergen
ALLERGEN_KEYWORDS: dict[AllergyType, list[str]] = {
    AllergyType.GLUTEN: [
        "wheat",
        "flour",
        "bread",
        "pasta",
        "spaghetti",
        "noodle",
        "noodles",
        "semolina",
        "couscous",
        "barley",
        "rye",
        "oat",
        "oats",
        "cracker",
        "breadcrumb",
        "bread crumb",
        "tortilla",
        "pita",
        "croissant",
        "pastry",
    ],
    AllergyType.LACTOSE: [
        "milk",
        "cheese",
        "cream",
        "butter",
        "yogurt",
        "yoghurt",
        "whey",
        "casein",
        "ghee",
        "parmesan",
        "mozzarella",
        "cheddar",
        "feta",
        "ricotta",
        "mascarpone",
        "brie",
        "camembert",
        "sour cream",
        "creme fraiche",
    ],
    AllergyType.TREE_NUTS: [
        "almond",
        "almonds",
        "walnut",
        "walnuts",
        "cashew",
        "cashews",
        "pecan",
        "pecans",
        "pistachio",
        "pistachios",
        "hazelnut",
        "hazelnuts",
        "macadamia",
        "brazil nut",
        "chestnut",
        "pine nut",
        "pine nuts",
    ],
    AllergyType.PEANUTS: [
        "peanut",
        "peanuts",
        "groundnut",
        "groundnuts",
        "peanut butter",
        "peanut oil",
    ],
    AllergyType.EGGS: [
        "egg",
        "eggs",
        "egg white",
        "egg yolk",
        "mayonnaise",
        "meringue",
        "custard",
        "aioli",
    ],
    AllergyType.FISH: [
        "fish",
        "salmon",
        "tuna",
        "cod",
        "haddock",
        "mackerel",
        "sardine",
        "sardines",
        "anchovy",
        "anchovies",
        "trout",
        "bass",
        "tilapia",
        "halibut",
        "sole",
        "fish sauce",
    ],
    AllergyType.SHELLFISH: [
        "shrimp",
        "prawn",
        "prawns",
        "lobster",
        "crab",
        "clam",
        "clams",
        "mussel",
        "mussels",
        "oyster",
        "oysters",
        "scallop",
        "scallops",
        "squid",
        "calamari",
        "octopus",
        "crayfish",
    ],
    AllergyType.SOY: [
        "soy",
        "soya",
        "soy sauce",
        "tofu",
        "tempeh",
        "edamame",
        "miso",
        "soybean",
        "soybeans",
    ],
    AllergyType.SESAME: [
        "sesame",
        "sesame seed",
        "sesame seeds",
        "sesame oil",
        "tahini",
        "halvah",
        "hummus",
    ],
    AllergyType.MUSTARD: [
        "mustard",
        "mustard seed",
        "mustard powder",
        "dijon",
    ],
    AllergyType.CELERY: [
        "celery",
        "celeriac",
        "celery salt",
        "celery seed",
    ],
}

# Exceptions for false positives
# Maps ingredient names to allergies/diets they should NOT trigger
EXCEPTIONS: dict[str, list[str]] = {
    # Coconut products are NOT dairy
    "coconut milk": ["lactose"],
    "coconut cream": ["lactose"],
    "coconut yogurt": ["lactose"],
    # Eggplant is NOT eggs
    "eggplant": ["eggs"],
    "egg plant": ["eggs"],
    "aubergine": ["eggs"],
    # Almond milk is NOT dairy (but still contains tree nuts)
    "almond milk": ["lactose"],
    # Soy milk is NOT dairy (but still contains soy)
    "soy milk": ["lactose"],
    # Oat milk is NOT dairy (but may contain gluten)
    "oat milk": ["lactose"],
}
